### PR TITLE
Added an options page to initially Configure the initial state of the Perspex Designer or disable it.

### PR DESCRIPTION
**Pull request by abdelkarim**
@ImaBrokeDude you're welcome to test this PR.

### CODE REVIEW

**Comment by abdelkarim** [comment]
What do you mean ??

**Comment by ImaBrokeDude** [comment]
`new[] { "paml", "designer" })]` should be `new[] { "xaml", "designer" })]` right?

**Comment by abdelkarim** [comment]
right, missed it.

**Comment by ImaBrokeDude** [comment]
Sick, I like it. I vote for a merge.

**Comment by ImaBrokeDude** [comment]
You can probably use the IWpfTextViewCreationListener to get the IWpfTextView from the code window not sure if that would help with the editorfactory or not.

**Comment by abdelkarim** [comment]
@ImaBrokeDude I don't think that would help with the current task, will keep that in mind for future improvements.

**Pull request merged**
